---
- name: Set yum cache to "keep"
  replace:
    dest: /etc/yum.conf
    regexp:  'keepcache=(.*)'
    replace: 'keepcache=1'
  when: connection == "docker"

- block: # Install firewalld and start service
  - name: Installing the firewalld command
    include_role:
       name: "lib/deploy"
       tasks_from: "rpms"
    with_dict: "{{ firewalld_packages }}"
    loop_control:
      loop_var: package

  - name: Starting firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes
  when: connection == "ssh" and ansible_distribution_major_version == "7"

- name: Installing the Unzip command
  include_role:
    name: "lib/deploy"
    tasks_from: "rpm"
  vars:
    rpm_app_name: "unzip"
    rpm_filename: "{{ item | basename }}"
  with_fileglob: "{{ cache_folder }}/{{ unzip_rpm }}"

- name: Installing EPEL Yum Repository
  include_role:
    name: "lib/deploy"
    tasks_from: "rpm"
  vars:
    rpm_app_name: "EPEL YUM Repository"
    rpm_filename: "{{ item | basename }}"
  with_fileglob: "{{ cache_folder }}/{{ epel_rpm }}"
...